# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sding/Bureau/stage_ingénieur/Cpp_traitement_image/detection_angle_cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sding/Bureau/stage_ingénieur/Cpp_traitement_image/detection_angle_cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sding/Bureau/stage_ingénieur/Cpp_traitement_image/detection_angle_cmake/CMakeFiles /home/sding/Bureau/stage_ingénieur/Cpp_traitement_image/detection_angle_cmake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sding/Bureau/stage_ingénieur/Cpp_traitement_image/detection_angle_cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named detection_contours

# Build rule for target.
detection_contours: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 detection_contours
.PHONY : detection_contours

# fast build rule for target.
detection_contours/fast:
	$(MAKE) -f CMakeFiles/detection_contours.dir/build.make CMakeFiles/detection_contours.dir/build
.PHONY : detection_contours/fast

YCBCr.o: YCBCr.cpp.o

.PHONY : YCBCr.o

# target to build an object file
YCBCr.cpp.o:
	$(MAKE) -f CMakeFiles/detection_contours.dir/build.make CMakeFiles/detection_contours.dir/YCBCr.cpp.o
.PHONY : YCBCr.cpp.o

YCBCr.i: YCBCr.cpp.i

.PHONY : YCBCr.i

# target to preprocess a source file
YCBCr.cpp.i:
	$(MAKE) -f CMakeFiles/detection_contours.dir/build.make CMakeFiles/detection_contours.dir/YCBCr.cpp.i
.PHONY : YCBCr.cpp.i

YCBCr.s: YCBCr.cpp.s

.PHONY : YCBCr.s

# target to generate assembly for a file
YCBCr.cpp.s:
	$(MAKE) -f CMakeFiles/detection_contours.dir/build.make CMakeFiles/detection_contours.dir/YCBCr.cpp.s
.PHONY : YCBCr.cpp.s

decomposition_canal.o: decomposition_canal.cpp.o

.PHONY : decomposition_canal.o

# target to build an object file
decomposition_canal.cpp.o:
	$(MAKE) -f CMakeFiles/detection_contours.dir/build.make CMakeFiles/detection_contours.dir/decomposition_canal.cpp.o
.PHONY : decomposition_canal.cpp.o

decomposition_canal.i: decomposition_canal.cpp.i

.PHONY : decomposition_canal.i

# target to preprocess a source file
decomposition_canal.cpp.i:
	$(MAKE) -f CMakeFiles/detection_contours.dir/build.make CMakeFiles/detection_contours.dir/decomposition_canal.cpp.i
.PHONY : decomposition_canal.cpp.i

decomposition_canal.s: decomposition_canal.cpp.s

.PHONY : decomposition_canal.s

# target to generate assembly for a file
decomposition_canal.cpp.s:
	$(MAKE) -f CMakeFiles/detection_contours.dir/build.make CMakeFiles/detection_contours.dir/decomposition_canal.cpp.s
.PHONY : decomposition_canal.cpp.s

haar_cascade.o: haar_cascade.cpp.o

.PHONY : haar_cascade.o

# target to build an object file
haar_cascade.cpp.o:
	$(MAKE) -f CMakeFiles/detection_contours.dir/build.make CMakeFiles/detection_contours.dir/haar_cascade.cpp.o
.PHONY : haar_cascade.cpp.o

haar_cascade.i: haar_cascade.cpp.i

.PHONY : haar_cascade.i

# target to preprocess a source file
haar_cascade.cpp.i:
	$(MAKE) -f CMakeFiles/detection_contours.dir/build.make CMakeFiles/detection_contours.dir/haar_cascade.cpp.i
.PHONY : haar_cascade.cpp.i

haar_cascade.s: haar_cascade.cpp.s

.PHONY : haar_cascade.s

# target to generate assembly for a file
haar_cascade.cpp.s:
	$(MAKE) -f CMakeFiles/detection_contours.dir/build.make CMakeFiles/detection_contours.dir/haar_cascade.cpp.s
.PHONY : haar_cascade.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... detection_contours"
	@echo "... YCBCr.o"
	@echo "... YCBCr.i"
	@echo "... YCBCr.s"
	@echo "... decomposition_canal.o"
	@echo "... decomposition_canal.i"
	@echo "... decomposition_canal.s"
	@echo "... haar_cascade.o"
	@echo "... haar_cascade.i"
	@echo "... haar_cascade.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

